version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build -x test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/healthy-0.0.1-SNAPSHOT.jar
#    - .ebextensions/**/*